# Generated by Django 5.0.4 on 2024-04-23 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='date_finish',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='date_next',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='date_start',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='date_send',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата следующей отправки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='time_finish',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='time_start',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
