# Generated by Django 5.0.4 on 2024-04-23 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_newsletter_date_finish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletter",
            name="time_finish",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="time_start",
        ),
        migrations.AddField(
            model_name="newsletter",
            name="date_finish",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата окончания"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="date_start",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="date_send",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата следующей отправки",
            ),
        ),
    ]
