# Generated by Django 4.2.2 on 2024-06-13 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_date_finish_newsletter_datetime_finish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="datetime_finish",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата окончания рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="datetime_send",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата отправки"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="datetime_start",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала рассылки"
            ),
        ),
    ]
