# Generated by Django 4.2.2 on 2024-06-14 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_alter_newsletter_datetime_finish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор рассылки",
            ),
        ),
    ]
