# Generated by Django 4.2.2 on 2024-06-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_message_options_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('set_is_active', 'Может менять активность рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
